[build]
  publish = "dist"

# Ensure sitemap/robots are served as static files, not caught by SPA routing
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

# SPA fallback - this must come AFTER the static file redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set correct MIME types and caching headers
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml; charset=utf-8"
    Cache-Control = "public, max-age=3600, must-revalidate"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
    Cache-Control = "public, max-age=3600, must-revalidate"